#!/bin/sh
lb config noauto \
    --mode debian \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --distribution trixie \
    --archive-areas "main contrib non-free-firmware" \
    --parent-mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --debian-installer live \
    --debian-installer-gui false \
    --bootappend-install "file=/cdrom/install/preseed.cfg auto=true priority=critical" \
    "${@}"
